server:
  port: ${PORT:8080}

spring:
  profiles:
    active: private
  data:
    web:
      pageable:
        size-parameter: limit
        one-indexed-parameters: true

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
