spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_schema: telegram_bot_payments_informing_schema
  flyway:
    default-schema: telegram_bot_payments_informing_schema
  #TODO: вся информация о запланированных джобах теряется, когда приложение не работает
  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          jobStore:
            class: "org.quartz.simpl.RAMJobStore"

telegram:
  telegram-api-url: https://api.telegram.org
  token: ${TOKEN}
  is-monitoring: ${IS_MONITORING}
  monitoring-chat-id: ${MONITORING_CHAT_ID}
  collecting-receipts-chat-id: ${COLLECTING_RECEIPTS_CHAT_ID}
  admins-chat-id: ${ADMINS_CHAT_ID}

google-sheets:
  sheet-id: ${GOOGLE_SHEET_ID}
  main-table-name: main
  pull-table-name: pull

#schedules
scheduled:
  user-time-zone: ${USER_TIME_ZONE}
  inform-overdue-start-time: ${INFORM_OVERDUE_START_TIME}
  inform-overdue-interval-minutes: ${INFORM_OVERDUE_INTERVAL_MINUTES}
  balance_decreaser-start-time: ${BALANCE_DECREASER_START_TIME}
  balance_decreaser-interval-minutes: ${BALANCE_DECREASER_INTERVAL_MINUTES}

logging:
  level:
    ru.apexman: DEBUG
